<?php

/**
 * PluginbsJobQueue
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class PluginbsJobQueue extends BasebsJobQueue
{
	/**
	 * process the current job
	 *
	 */
	public function process() {
		//Init status in db
		$timer = new sfTimer();
		$timer->startTimer();
		
		$hasError = false;
		$this->setStatus('in_progress');
		$this->setExecutedAt(date('Y-m-d H:m:s'));
		$this->save();

		//process the job
		try {
	   		$params = unserialize($this->getJobParams());
	        $table = Doctrine_Core::getTable($this->getTableClassName());
	        $table->{$this->getFunctionName()}($params);
		} catch (Exception $e) {
			$hasError = true;
			$this->setStatus('has_error');
			$this->setNote($e->__toString());
			$this->save();
		}
		
		if (!$hasError) {
	        //finalise the status in db
	        $this->setStatus('done');
	        $this->setDuration($timer->addTime());
			$this->save();
		}
		return true;
	}
}
